/*

 TILES_TITLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 63

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __TILES_Title_h_INCLUDE
#define __TILES_Title_h_INCLUDE

#include <gb/gb.h>
BANKREF_EXTERN(TILES_Title)

#define TILES_TitleLen 64

/* Start of tile array. */
extern const unsigned char TILES_Title[];

#endif

/* End of TILES_TITLE.H */
