/*

 TILES_DIGITS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __TILES_digits_h_INCLUDE
#define __TILES_digits_h_INCLUDE

/* Bank of tiles. */
#define TILES_digitsBank 0
/* Start of tile array. */
extern const unsigned char TILES_digits[];
#define TILES_digitsLen 10

#endif

/* End of TILES_DIGITS.H */
