/*

 MAP_TITLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : TILES_Title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __MAP_Title_h_INCLUDE
#define __MAP_Title_h_INCLUDE

#include <gb/gb.h>
BANKREF_EXTERN(MAP_Title)

#define MAP_TitleWidth 20
#define MAP_TitleHeight 18
#define MAP_TitleBank 0

extern const unsigned char MAP_Title[];

#endif

/* End of MAP_TITLE.H */
