/*

 TILE-TITLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tile_title_h_INCLUDE
#define __tile_title_h_INCLUDE

#include <gb/gb.h>
BANKREF_EXTERN(TILES_Title)

/* Start of tile array. */
extern const unsigned char TILES_Title[];

#endif

/* End of TILE-TITLE.H */
